FROM mcr.microsoft.com/devcontainers/ruby:dev-4

RUN apt-get update && apt-get install -y postgresql-common \
    && yes | /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh \
    && apt-get install -y postgresql-client-18 \
    && rm -rf /var/lib/apt/lists/*
